Repository modelscope/swift, pull requests merged in 2024-04, with the labels that each got.

#695 fix device_map 4 (qwen-vl)
  docs/source/Multi-Modal/minicpm-v最佳实践.md
  swift/llm/utils/model.py
  swift/llm/utils/utils.py
Labels: bug

#712 [Feat] Compatible with Hugging Face & update more models
  README.md
  README_CN.md
  docs/source/LLM/HuggingFace生态兼容.md
  docs/source/LLM/LLM微调文档.md
  docs/source/LLM/index.md
  docs/source/LLM/支持的模型和数据集.md
  docs/source/LLM/自定义与拓展.md
  docs/source_en/LLM/Compat-HF.md
  docs/source_en/LLM/Customization.md
  docs/source_en/LLM/Supported-models-datasets.md
  docs/source_en/LLM/index.md
  scripts/utils/run_dataset_info.py
  scripts/utils/run_model_info.py
  swift/llm/dpo.py
  swift/llm/ds_config/zero3_offload.json
  swift/llm/export.py
  swift/llm/infer.py
  swift/llm/sft.py
  swift/llm/utils/argument.py
  swift/llm/utils/dataset.py
  swift/llm/utils/model.py
  swift/llm/utils/template.py
  swift/llm/utils/utils.py
  swift/llm/utils/vllm_utils.py
Labels: enhancement, more models

#737 DeepSeek-vl supports multi-image and plain text data
  docs/source/Multi-Modal/deepseek-vl最佳实践.md
  docs/source/Multi-Modal/llava最佳实践.md
  docs/source/Multi-Modal/qwen-audio最佳实践.md
  docs/source/Multi-Modal/qwen-vl最佳实践.md
  docs/source_en/Multi-Modal/deepseek-vl-best-practice.md
  docs/source_en/Multi-Modal/llava-best-practice.md
  docs/source_en/Multi-Modal/qwen-audio-best-practice.md
  docs/source_en/Multi-Modal/qwen-vl-best-practice.md
  swift/llm/utils/template.py
Labels: enhancement

#739 support llama3
  README.md
  README_CN.md
  docs/source/LLM/支持的模型和数据集.md
  docs/source_en/LLM/Supported-models-datasets.md
  swift/llm/utils/model.py
  swift/llm/utils/template.py
Labels: more models

#749 fix msbench bug
  swift/llm/utils/dataset.py
Labels: bug

#748 Support chatglm3-6b-128k
  README.md
  README_CN.md
  docs/source/LLM/LLM量化文档.md
  docs/source/LLM/NPU推理与微调最佳实践.md
  docs/source/LLM/命令行参数.md
  docs/source/LLM/支持的模型和数据集.md
  docs/source_en/LLM/Command-line-parameters.md
  docs/source_en/LLM/LLM-quantization.md
  docs/source_en/LLM/NPU-best-practice.md
  docs/source_en/LLM/Supported-models-datasets.md
  requirements/framework.txt
  swift/cli/main.py
  swift/llm/app_ui.py
  swift/llm/deploy.py
  swift/llm/dpo.py
  swift/llm/eval.py
  swift/llm/export.py
  swift/llm/infer.py
  swift/llm/rome.py
  swift/llm/sft.py
  swift/llm/tuner.py
  swift/llm/utils/argument.py
  swift/llm/utils/dataset.py
  swift/llm/utils/model.py
  swift/llm/utils/template.py
  swift/llm/utils/utils.py
  swift/llm/utils/vllm_utils.py
Labels: more models

#793 fix `swift infer --model_type` & vllm bugs
  swift/llm/infer.py
Labels: bug
